const dsCharacters = [
  {
    name: 'Abysswalker Artorias',
    img: 'https://www.giantbomb.com/a/uploads/original/16/163828/2334729-tumblr_m9cfdpslwn1qlhor5o2_1280.jpg',
    rarity: 'normal',
    trunfo: false,
    attr1: '50',
    attr2: '50',
    attr3: '50',
    description: 'Once a loyal knight to Gwyn, Lord of Sunlight, Knight Artorias fell to the Abyss trying to rescue Princess Dusk of Oolacile.',
  },
  {
    name: 'Dragon Slayer Ornstein',
    img: 'https://www.giantbomb.com/a/uploads/scale_small/5/58259/2114095-1323539241862.png',
    rarity: 'normal',
    trunfo: false,
    attr1: '50',
    attr2: '50',
    attr3: '50',
    description: 'Dragon Slayer Ornstein is one of the four knights of Gwyn lord of Sunlight. Fought alongside Executioner Smough.',
  },
  {
    name: 'Executioner Smough',
    img: 'https://www.giantbomb.com/a/uploads/scale_small/5/58259/2113827-__image.jpg',
    rarity: 'normal',
    trunfo: false,
    attr1: '50',
    attr2: '50',
    attr3: '50',
    description: 'Executioner Smough is part of the Princess Guard along with Dragon Slayer Ornstein.',
  },
  {
    name: 'Gwyn',
    img: 'https://www.giantbomb.com/a/uploads/scale_small/15/154387/2210319-io7u8.jpg',
    rarity: 'normal',
    trunfo: true,
    attr1: '50',
    attr2: '50',
    attr3: '50',
    description: 'The former Lord of Sunlight and ruler of Lordran who became a Hollow now known as the Lord of Cinder. He is the final boss of Dark Souls.',
  },
  {
    name: 'Manus, Father of The Abyss',
    img: 'https://www.giantbomb.com/a/uploads/scale_small/16/163828/2351393-manus.jpg',
    rarity: 'raro',
    trunfo: false,
    attr1: '50',
    attr2: '50',
    attr3: '50',
    description: 'The primeval human. Final boss of Artorias of the Abyss.',
  },
  {
    name: 'Gravelord Nito',
    img: 'https://darksouls.wiki.fextralife.com/file/Dark-Souls/Boss_0021_Nito.jpg',
    rarity: 'raro',
    trunfo: false,
    attr1: '50',
    attr2: '50',
    attr3: '50',
    description: 'Holder of one of the four Lord Souls, Gravelord Nito was among the lords to wage war against the dragons. As the Lord of Death, Nito rules over the dead in The Catacombs and resides within the Tomb of Giants.',
  },
  {
    name: 'Soul of Cinder',
    img: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/Soul%20of%20Cinder.jpg',
    rarity: 'muito raro',
    trunfo: false,
    attr1: '50',
    attr2: '50',
    attr3: '50',
    description: 'The Soul of Cinder is seen as the amalgamation of all the Lords of Cinder, with a variety of Dark Dialectics spells and moveset.',
  },

];

export default dsCharacters;
